### ISSUE TITLE
Button: Icon missing

### ISSUE THREAD

**Issue by GHNJ** [leocb/MaterialSkin#178]
Hi, testing out the latest version of the .dll (2.2.0) and all of the buttons appear to be "missing" the icons I've chosen for them. 

I've rebuilt solution/project and added new buttons and applied an icon, but they still do not show (even at runtime). 

Wondering if this is a known behavior, or if there's a suggestion to fixing it, so I can use the newest version. 

thanks!

**Comment by GHNJ** [comment]
sure, here are two screen grabs with info; the icons are two .png's.

![2021-05-28 14_25_52-Window](https://user-images.githubusercontent.com/25934500/120029106-a86a5180-bfc3-11eb-8c30-a881aae04af4.png)
![2021-05-28 14_27_01-Window](https://user-images.githubusercontent.com/25934500/120029109-a902e800-bfc3-11eb-8b65-c00e69c4bb6a.png)

**Comment by orapps44** [comment]
Previously images greater than 24px where automatically resized. 
This wasn't the case since grey filter has been introduced.
Icon missing has been fixed with PR #179 and his now merged into master.

Try to recompile from master and let me know.

Same correction is also needed for TextBox (leading and trailing icon)

**Comment by GHNJ** [comment]
perfect, thanks so much for the quick TaT. 
Will compile and comment back if further issues persist. 

thanks!
